version: '3.8'

services:

  recommendAlg:
    build:
      context: ./recommendAlg
    container_name: recommendAlg
    networks:
      - app_network

  scraper:
    build:
      context: ./scraper
    container_name: scraper
    networks:
      - app_network
    environment:
      - MONGO_URI=${MGO_URI}

  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - app_network
    depends_on:
      - recommendAlg
    environment:
      - MONGO_URI=${MGO_URI}

  client:
    build:
      context: ./client
    container_name: client
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - recommendAlg
    environment:
      - BACKEND_URL=http://backend:5000
      - RECOMMENDALG_URL=http://recommendAlg:5000

networks:
  app_network:
